import numpy as np
import matplotlib.pyplot as plt

"""
The following code generates a plot representing the
probability distribution of the number of steps in a
staircase generated by a simulation. The x-axis of the
plot represents the number of steps in the staircase,
and the y-axis represents the probability of that number
of steps occurring in the simulation.
"""

# Evaluating the formula floor((10*1.585^-x)+1)
data = {'1':50,
        '2':16.666,
        '3':9.754,
        '4':6.906,
        '5':5.35,
        '6':4.4,
        '7':3.71,
        '8':3.22}

courses = list(data.keys())
values = list(data.values())
  
fig = plt.figure(figsize = (3, 3))
 
# creating the bar plot
plt.bar(courses, values, color='grey', 
        width = 0.9)
 
plt.xlabel("No. of Steps")
plt.ylabel("Proportion of Occurrence (%)")
plt.tight_layout()
plt.show()

